### PR TITLE
adjust for Python 3

### PR DESCRIPTION
**Pull request by csaftoiu**
The example works on Python 3 after I made these changes. It should still work in Python 2 also, but not tested.

### CODE REVIEW

**Comment by flaviostutz** [comment]
Please, accept this pull request...

**Comment by daniel-j-h** [comment]
Ping - any updates here?

The package is currently broken on Python3 and the changes needed for a fix are quite minor.

**Comment by exilis** [comment]
Thanks @csaftoiu , and sorry for the long silence... I just released it to PyPl as [selectivesearch==0.0.4](https://pypi.python.org/pypi/selectivesearch)

( also confirmed that it worked with python2 as well )

**Comment by csaftoiu** [comment]
Alsome :) No worries, I know how it goes. Cheers

**Pull request merged**
